cleanup "simplify"

diff --git a/.github/actions/restore-cache-azcopy/action.yml b/.github/actions/restore-cache-azcopy/action.yml
--- a/.github/actions/restore-cache-azcopy/action.yml
+++ b/.github/actions/restore-cache-azcopy/action.yml
@@ -26,16 +26,8 @@ runs:
       path: sas-token
       key: sas-key-${{ inputs.target-platform }}-${{ github.run_number }}-${{ github.run_attempt }}
       enableCrossOsArchive: true
-  - name: Set sas-token env variable
-    shell: bash
-    run: |
-      sas_token=$(cat sas-token)
-      if [ -z $sas-token ]; then
-        echo "SAS Token not found; exiting src cache download early..."
-        exit 1
-      fi
-      echo "SAS_TOKEN=$sas-token" >> $GITHUB_ENV
-  - name: Download Src Cache from AKS
+  - name: Download Src Cache from AKS (macos)
+    if: ${{ inputs.target-platform == 'macos' }}
     # The cache will always exist here as a result of the checkout job
     # Either it was uploaded to Azure in the checkout job for this commit
     # or it was uploaded in the checkout job for a previous commit.
@@ -44,17 +36,24 @@ runs:
       timeout_minutes: 30
       max_attempts: 3
       retry_on: error
+      shell: bash
       command: |
+        sas_token=$(cat sas-token)
+        if [ -z $sas-token ]; then
+          echo "SAS Token not found; exiting src cache download early..."
+          exit 1
+        else
+          azcopy copy --log-level=ERROR \
+          "https://${{ env.AZURE_AKS_CACHE_STORAGE_ACCOUNT }}.file.core.windows.net/${{ env.AZURE_AKS_CACHE_SHARE_NAME }}/${{ env.CACHE_PATH }}?$sas_token" $DEPSHASH.tar
+        fi
 
-        azcopy copy --log-level=ERROR \
-          "https://${{ env.AZURE_AKS_CACHE_STORAGE_ACCOUNT }}.file.core.windows.net/${{ env.AZURE_AKS_CACHE_SHARE_NAME }}/${{ env.CACHE_PATH }}?${{ env.SAS_TOKEN }}" "${{ env.DEPSHASH}}.tar"
     env:
       AZURE_AKS_CACHE_STORAGE_ACCOUNT: f723719aa87a34622b5f7f3
       AZURE_AKS_CACHE_SHARE_NAME: pvc-f6a4089f-b082-4bee-a3f9-c3e1c0c02d8f
-  - name: Clean SAS Key (macos)
+  - name: Clean SAS Key
     shell: bash
     run: rm -f sas-token
-  - name: Unzip and Ensure Src Cache (macOS)
+  - name: Unzip and Ensure Src Cache
     if: ${{ inputs.target-platform == 'macos' }}
     shell: bash
     run: |
@@ -85,7 +84,7 @@ runs:
       echo "Wiping Electron Directory"
       rm -rf src/electron
 
-  - name: Unzip and Ensure Src Cache (Windows)
+  - name: Unzip and Ensure Src Cache
     if: ${{ inputs.target-platform == 'win' }}
     shell: powershell
     run: |
